name: CI

on:
  push:
    branches: [main]
jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: npm-modules-${{ hashFiles('package-lock.json') }}

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install npm dependencies
        run: npm i

      - name: Build
        run: npm run build --prod

      - name: Test
        run: npm run test

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: deploy-dist
          path: dist

  deploy:
    name: Deploy
    needs: [test-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/download-artifact@v2

      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy-dist

      - name: Setup Google Cli
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Upload Files
        run: |
          gsutil cp -r $GITHUB_WORKSPACE/deploy-dist/deploy-angular-app/* gs://deploy-angular-app
